const { ROLES, ADMIN_ROLES } = require('./roles');

/**
 * Granular Permission Matrix for Resources and Operations
 * Maps resources and operations to arrays of permitted roles.
 * Modify access permissions centrally here without changing route definitions or controllers.
 * Both ADMIN and OWNER share identical full administrative permissions via ADMIN_ROLES.
 */
const PERMISSIONS = Object.freeze({
  USER: {
    READ: ADMIN_ROLES,
    UPDATE_ROLE: ADMIN_ROLES,
    UPDATE_LAPAK: ADMIN_ROLES,
    DELETE: ADMIN_ROLES,
  },
  LAPAK: {
    CREATE: ADMIN_ROLES,
    READ: Object.freeze([...ADMIN_ROLES, ROLES.SPG, ROLES.VIAR, ROLES.PRODUKSI]),
    UPDATE: ADMIN_ROLES,
    DELETE: ADMIN_ROLES,
  },
  PRODUK: {
    CREATE: ADMIN_ROLES,
    READ: ADMIN_ROLES,
    UPDATE: ADMIN_ROLES,
    UPDATE_STATUS: ADMIN_ROLES,
    DELETE: ADMIN_ROLES,
  },
  KATEGORI: {
    CREATE: ADMIN_ROLES,
    READ: ADMIN_ROLES,
    UPDATE: ADMIN_ROLES,
    DELETE: ADMIN_ROLES,
  },
  SATUAN: {
    CREATE: ADMIN_ROLES,
    READ: Object.freeze([...ADMIN_ROLES, ROLES.PRODUKSI]),
    UPDATE: ADMIN_ROLES,
    DELETE: ADMIN_ROLES,
  },
  PENGIRIMAN: {
    CREATE: ADMIN_ROLES,
    READ: Object.freeze([...ADMIN_ROLES, ROLES.PRODUKSI, ROLES.VIAR, ROLES.SPG]),
    UPDATE: Object.freeze([...ADMIN_ROLES, ROLES.PRODUKSI, ROLES.VIAR, ROLES.SPG]),
    UPDATE_STATUS: Object.freeze([...ADMIN_ROLES, ROLES.PRODUKSI, ROLES.VIAR, ROLES.SPG]),
    DELETE: ADMIN_ROLES,
  },
  PENGIRIMAN_DETAIL: {
    READ: Object.freeze([...ADMIN_ROLES, ROLES.PRODUKSI, ROLES.VIAR, ROLES.SPG]),
  },
  PENERIMAAN: {
    CREATE: Object.freeze([...ADMIN_ROLES, ROLES.SPG]),
    READ: Object.freeze([...ADMIN_ROLES, ROLES.PRODUKSI, ROLES.VIAR, ROLES.SPG]),
    UPDATE: Object.freeze([...ADMIN_ROLES, ROLES.SPG]),
    DELETE: ADMIN_ROLES,
  },
  STOK_LAPAK: {
    CREATE: ADMIN_ROLES,
    READ: Object.freeze([...ADMIN_ROLES, ROLES.PRODUKSI, ROLES.SPG]),
    UPDATE: Object.freeze([...ADMIN_ROLES, ROLES.SPG]),
    DELETE: ADMIN_ROLES,
  },
  COUNTERS: {
    READ: ADMIN_ROLES,
    DELETE: ADMIN_ROLES,
  },
  PENJUALAN: {
    CREATE: Object.freeze([...ADMIN_ROLES, ROLES.SPG]),
    READ: Object.freeze([...ADMIN_ROLES, ROLES.PRODUKSI, ROLES.VIAR, ROLES.SPG]),
    UPDATE: ADMIN_ROLES,
    UPLOAD_BUKTI: Object.freeze([...ADMIN_ROLES, ROLES.SPG]),
    DELETE: ADMIN_ROLES,
  },
  PENJUALAN_DETAIL: {
    READ: Object.freeze([...ADMIN_ROLES, ROLES.PRODUKSI, ROLES.VIAR, ROLES.SPG]),
  },
  ABSENSI: {
    CREATE: Object.freeze([...ADMIN_ROLES, ROLES.SPG, ROLES.VIAR, ROLES.PRODUKSI]),
    READ: Object.freeze([...ADMIN_ROLES, ROLES.PRODUKSI, ROLES.VIAR, ROLES.SPG]),
    UPDATE: ADMIN_ROLES,
    CLOCK_OUT: Object.freeze([...ADMIN_ROLES, ROLES.SPG, ROLES.VIAR, ROLES.PRODUKSI]),
    UPLOAD_FOTO: Object.freeze([...ADMIN_ROLES, ROLES.SPG, ROLES.VIAR, ROLES.PRODUKSI]),
    DELETE: ADMIN_ROLES,
  },
  CLOSING: {
    CREATE: Object.freeze([...ADMIN_ROLES, ROLES.SPG]),
    READ: Object.freeze([...ADMIN_ROLES, ROLES.SPG]),
    UPDATE: Object.freeze([...ADMIN_ROLES, ROLES.SPG]),
    UPDATE_STATUS: ADMIN_ROLES,
    DELETE: ADMIN_ROLES,
  },
  PAYROLL: {
    CREATE: ADMIN_ROLES,
    READ: Object.freeze([...ADMIN_ROLES, ROLES.SPG, ROLES.VIAR, ROLES.PRODUKSI]),
    UPDATE: ADMIN_ROLES,
    UPDATE_STATUS: ADMIN_ROLES,
    DELETE: ADMIN_ROLES,
  },
  SLIP_GAJI: {
    CREATE: ADMIN_ROLES,
    READ: Object.freeze([...ADMIN_ROLES, ROLES.SPG, ROLES.VIAR, ROLES.PRODUKSI]),
    UPLOAD_FILE: ADMIN_ROLES,
    DELETE: ADMIN_ROLES,
  },
});

module.exports = {
  PERMISSIONS,
};
